
require 'cocoapods'
source 'https://github.com/CocoaPods/Specs.git'
#source 'http://192.168.1.33:9090/Pods/Specs.git'
source 'https://github.com/Leon0206/MDSpecs.git'
#cdn
#source 'https://cdn.cocoapods.org/'

platform :ios, '9.0'

inhibit_all_warnings!
use_modular_headers!

eval(File.open('PodDevExtension.rb').read) if File.exist? 'PodDevExtension.rb'

def shared_pods
  ENV['use_binary'] = '1'
  ENV['MDCommonKit_use_binary'] = '1'
  ENV['EasyLayout_use_binary'] = '1'
  #业务代码库
  pod 'MDHomeProject', '~> 0.0.1'
  
  #业务组件、解决方案
  #  pod 'XYFelix', '~> 1.0.0'
  
  pod 'MDPageMaster', '2.0.18'
   
  pod 'MDStatePageKit', '~> 1.0.0'
  
  pod 'ReactiveDataBoard', '~> 4.0.0'
  
  pod 'MDReactPageKit', '~> 1.0.0'

  pod 'MDEasyCache', '~> 1.0.0'
  
  pod 'EasyLayout', '~> 1.0.0'
  
  pod 'MDCommonKit', '~> 1.0.0'
  
  #React-Native
#  pod 'React', :path => '../node_modules/react-native/React.podspec'
#  pod 'React-Core', :path => '../node_modules/react-native/React-Core.podspec'
#  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact/React-cxxreact.podspec'
#  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS/React-RCTActionSheet.podspec'
#  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation/React-RCTAnimation.podspec'
#  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor/React-jsiexecutor.podspec'
#  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector/React-jsinspector.podspec'
#  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
#  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
#  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
#  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
#  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
#  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
#  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
#  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
#  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
#  pod 'Yoga', :path => '/Users/lizitao/Desktop/MDMainProject/MDProject/node_modules/react-native/ReactCommon/yoga'

  #第三方
 # pod 'WebViewJavascriptBridge', '~> 6.0'
 # pod 'WKWebViewJavascriptBridge', '~> 6.0'
  pod 'ReactiveObjC', '3.1.0'
  pod 'TMCache', '2.1.0'
  pod 'PINCache', '2.0'
  pod 'SDWebImage', '4.4.2'
  pod 'Masonry', '0.6.1'
  pod 'JSPatch'
  pod 'Aspects', '1.4.1'
  pod 'SSZipArchive', '0.4.0'
  pod 'AFNetworking','3.2.1'

end

target 'MDProject' do
    shared_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == 'DailyBuild'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'TEST=1']
            end
        end
    end
end
